// Manual augmentations to the Cloudflare Env generated by `wrangler types`
// (worker-configuration.d.ts is regenerated and should not be edited by hand).
declare global {
	namespace Cloudflare {
		interface Env {
			GROQ_API_KEY: string;
		}
	}

	// Mirror all Cloudflare.Env bindings (generated by `wrangler types` +
	// augmented above) onto CloudflareEnv, so `getCloudflareContext().env`
	// from @opennextjs/cloudflare is fully typed.
	interface CloudflareEnv extends Cloudflare.Env {}
}

export {};
