// Manual augmentations to the Cloudflare Env generated by `wrangler types`
// (worker-configuration.d.ts is regenerated and should not be edited by hand).
declare global {
	namespace Cloudflare {
		interface Env {
			GROQ_API_KEY: string;
		}
	}
}

export {};
