import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { HatGlasses, Scale, GitFork, BookMarked, Languages } from 'lucide-react';
import Image from "next/image";
import Link from "next/link";
import MarkdownComponent from "./markdown";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { getTranslations } from "next-intl/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

//Metadata only work on Server components, might improve SEO
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{locale: string}>;
}>) {
  const {locale} = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const t = await getTranslations({ locale, namespace: 'layout' }) 

  return (
    <html lang={`${locale}`}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextIntlClientProvider>
          <div className="flex flex-col w-full h-screen">
            <div className="flex flex-row w-full h-8 shrink-0 bg-topbar items-center gap-6 px-2 border border-solid border-set-100">
              <Image src="/favicon.ico"
                alt="Brand Logo"
                width={24}
                height={24}
              />
              <Link href={"/"}>
                <p className="text-white font-normal">{t('home')}</p>
              </Link>
              <Link href={"/rasmus-website-fig"}>
                <p className="text-white font-normal">{t('projects')}</p>
              </Link>
              <p className="text-white font-normal">{t('contact')}</p>
            </div>
            <div className="flex flex-1 min-h-0 flex-row w-full">
              <div className="flex flex-col w-60 shrink-0 bg-files">
                <p className="text-white font-normal">mobileminigames.cs</p>
                <p className="text-white font-normal">hotreload.cs</p>
                <p className="text-white font-normal">athenegpt.go</p>
              </div>
              <div className="min-h-0 flex-1 overflow-auto bg-script">
                <MarkdownComponent>
                  {children}
                </MarkdownComponent>
              </div>
            </div>
            <div className="w-full h-5 shrink-0 bg-botbar flex flex-row items-center gap-6 px-4 border border-solid border-set-100">
              <a href="https://github.com"
                target="_blank"
                rel="noopener noreferrer"
                className="flex flex-row items-center gap-1.5 cursor-pointer hover:opacity-80 transition-opacity"
              >
                <GitFork size={14} />
                <p className="text-white font-normal">master</p>
                <BookMarked size={14} />
                <p className="text-white font-normal">github.com/rasmus-website</p>
              </a>
              <div className="flex flex-row items-center gap-1.5 cursor-pointer hover:opacity-80 transition-opacity">
                <Languages size={14} />
                <p className="text-white font-normal">English</p>
              </div>
              <div className="flex flex-row items-center gap-1.5 cursor-pointer hover:opacity-80 transition-opacity">
                <Scale size={14} />
                <p className="text-white font-normal">{t('imprint')}</p>
              </div>
              <div className="flex flex-row items-center gap-1.5 cursor-pointer hover:opacity-80 transition-opacity">
                <HatGlasses size={14} />
                <p className="text-white font-normal">{t('privacy')}</p>
              </div>
            </div>
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
